[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "plotly>=6.0.0",
    "streamlit>=1.41.1",
    "sympy>=1.13.3",
]
